### ISSUE TITLE
Error when catching a fish

### ISSUE THREAD

**Issue by baailey** [Oheers/EvenMoreFish#113]
09.03 16:51:12 [Server] ERROR [EvenMoreFish] Could not fetch fishing data for: baailey
09.03 16:51:12 [Server] WARN java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because the return value of "java.util.Map.get(Object)" is null
09.03 16:51:12 [Server] WARN at even-more-fish-1.5.0.1.jar//com.oheers.fish.fishing.FishingProcessor$1.run(FishingProcessor.java:223)
09.03 16:51:12 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
09.03 16:51:12 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
09.03 16:51:12 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
09.03 16:51:12 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
09.03 16:51:12 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
09.03 16:51:12 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)

Running 1.5.0.1

**Comment by Oheers** [comment]
Hi baailey, apologies for the late reply I've been quite busy lately. This is a known bug but I'm still trying to gather information - do you have a /data/ folder, and if so does it contain a file for your UUID in there?

- Oheers

**Comment by baailey** [comment]
I do, it only has [] in it. I'll contact you on discord for quicker responses.

**Comment by Yaseria** [comment]
We have the same problems.

```
[12:51:36 ERROR]: [EvenMoreFish] Could not fetch fishing data for: Tali_Sora
[12:51:36 WARN]: java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because the return value of "java.util.Map.get(Object)" is null
[12:51:36 WARN]:        at even-more-fish-1.5.0.12.jar//com.oheers.fish.fishing.FishingProcessor$1.run(FishingProcessor.java:224)
[12:51:36 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[12:51:36 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[12:51:36 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:51:36 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:51:36 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:51:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```
The /data/ folder exist

**Comment by Oheers** [comment]
This is believed to be fixed in the latest dev build.
