### ISSUE TITLE
Cannot invoke "java.util.List.add(Object)" because the return value of "java.util.Map.get(Object)" is null

### ISSUE THREAD

**Issue by mibby** [Oheers/EvenMoreFish#115]
Paper dev 257 (1.18.2)
EvenMoreFish dev 10 
https://ci.codemc.io/view/All/job/Oheers/job/EvenMoreFish/10/

EvenMoreFish was spamming this error a couple hundred times in my logs.

```
[18:04:48] [Craft Scheduler Thread - 1794 - EvenMoreFish/ERROR]: [EvenMoreFish] Could not fetch fishing data for: ivyrose333
[18:04:48] [Craft Scheduler Thread - 1794 - EvenMoreFish/WARN]: java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because the return value of "java.util.Map.get(Object)" is null
[18:04:48] [Craft Scheduler Thread - 1794 - EvenMoreFish/WARN]: 	at even-more-fish-1.5.0.12.jar//com.oheers.fish.fishing.FishingProcessor$1.run(FishingProcessor.java:224)
[18:04:48] [Craft Scheduler Thread - 1794 - EvenMoreFish/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[18:04:48] [Craft Scheduler Thread - 1794 - EvenMoreFish/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:04:48] [Craft Scheduler Thread - 1794 - EvenMoreFish/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:04:48] [Craft Scheduler Thread - 1794 - EvenMoreFish/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:04:48] [Craft Scheduler Thread - 1794 - EvenMoreFish/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:04:48] [Craft Scheduler Thread - 1794 - EvenMoreFish/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by mibby** [comment]
There was, but I deleted the /data/ folder and migrated to a MySQL database to try and fix the data loading/saving error. Sorry! The file was most likely ``[]`` empty though.

**Comment by Oheers** [comment]
Oh no worries, a few other people mentioned things that might be causing this, I'm going to try and look into this later today.

**Comment by Oheers** [comment]
@mibby I've got a load of debug messages in the latest commit, built on the [jenkins server](https://ci.codemc.io/job/Oheers/job/EvenMoreFish/) on the latest build (1.5.0.20) - could you reply with the results of what gets sent when a user leaves please?

**Comment by Oheers** [comment]
This is believed to be fixed in the latest dev build.
