### ISSUE TITLE
EvenMoreFish v1.5.0.29 generated an exception when a competition ended.,

### ISSUE THREAD

**Issue by TomLewis** [Oheers/EvenMoreFish#120]
First time testing a competition with `/emf admin competition start 600 largest_fish` and at the end, no prizes were given out, but an exception was generated.

```
[22:26:40] [Server thread/WARN]: [EvenMoreFish] Task #6206 for EvenMoreFish v1.5.0.29 generated an exception
java.lang.NoClassDefFoundError: me/clip/placeholderapi/PlaceholderAPI
	at com.oheers.fish.competition.reward.Reward.run(Reward.java:70) ~[even-more-fish-1.5.0.29.jar:?]
	at com.oheers.fish.competition.Competition.handleRewards(Competition.java:533) ~[even-more-fish-1.5.0.29.jar:?]
	at com.oheers.fish.competition.Competition.end(Competition.java:98) ~[even-more-fish-1.5.0.29.jar:?]
	at com.oheers.fish.competition.Competition.processCompetitionSecond(Competition.java:155) ~[even-more-fish-1.5.0.29.jar:?]
	at com.oheers.fish.competition.Competition.access$000(Competition.java:21) ~[even-more-fish-1.5.0.29.jar:?]
	at com.oheers.fish.competition.Competition$1.run(Competition.java:111) ~[even-more-fish-1.5.0.29.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.1.jar:git-Purpur-1564]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.1.jar:git-Purpur-1564]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1584) ~[purpur-1.18.1.jar:git-Purpur-1564]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1564]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1507) ~[purpur-1.18.1.jar:git-Purpur-1564]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1294) ~[purpur-1.18.1.jar:git-Purpur-1564]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1564]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.clip.placeholderapi.PlaceholderAPI
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 14 more
```

**Comment by Oheers** [comment]
Hey there, is your server running the latest version of placeholder API? If not could you let  me know if the issue persists with that version please? Cheers 👍

**Comment by TomLewis** [comment]
This was on my test server, and it looks like PlaceholderAPI isnt even installed! So its a hard dependency then!
Maybe put in a check into the plugin if its not installed? I will install it and test again!

**Comment by TomLewis** [comment]
That was it, seems to run prizes now. I suggest checking for placeholder API at boot, and if it is 100% required, then disable the plugin maybe and tell people its required as a hard dependency? or just disable placeholderAPI things if its not installed.

**Comment by Oheers** [comment]
Ah glad that's working for you then :) It shouldn't be a hard dependency, so I'll leave this open and have a look what might be causing it to act like that,

**Comment by sarhatabaot** [comment]
Fixed a while back but issue was never closed.
