### ISSUE TITLE
IllegalArgumentException: effect type cannot be null

### ISSUE THREAD

**Issue by mibby** [Oheers/EvenMoreFish#134]
EvenMoreFish dev 49
https://ci.codemc.io/view/All/job/Oheers/job/EvenMoreFish/49/

https://github.com/Oheers/EvenMoreFish/blob/master/src/main/resources/fish.yml#L51
```
    Electric Eel:
      message: "&b*Zap!*"
      effect: "INSTANT_DAMAGE:1:1"
```

```
[05:48:17] [Server thread/WARN]: java.lang.IllegalArgumentException: effect type cannot be null
[05:48:17] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[05:48:17] [Server thread/WARN]: 	at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:80)
[05:48:17] [Server thread/WARN]: 	at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:51)
[05:48:17] [Server thread/WARN]: 	at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:101)
[05:48:17] [Server thread/WARN]: 	at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:114)
[05:48:17] [Server thread/WARN]: 	at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:126)
[05:48:17] [Server thread/WARN]: 	at even-more-fish-1.5.0.50.jar//com.oheers.fish.fishing.items.Fish.checkEffects(Fish.java:167)
[05:48:17] [Server thread/WARN]: 	at even-more-fish-1.5.0.50.jar//com.oheers.fish.fishing.items.Fish.init(Fish.java:181)
[05:48:17] [Server thread/WARN]: 	at even-more-fish-1.5.0.50.jar//com.oheers.fish.fishing.FishingProcessor.getFish(FishingProcessor.java:134)
[05:48:17] [Server thread/WARN]: 	at even-more-fish-1.5.0.50.jar//com.oheers.fish.fishing.FishingProcessor.process(FishingProcessor.java:42)
[05:48:17] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38)
[05:48:17] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[05:48:17] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[05:48:17] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671)
[05:48:17] [Server thread/WARN]: 	at net.minecraft.world.entity.projectile.EntityFishingHook.a(EntityFishingHook.java:507)
[05:48:17] [Server thread/WARN]: 	at net.minecraft.world.item.ItemFishingRod.a(ItemFishingRod.java:30)
[05:48:17] [Server thread/WARN]: 	at net.minecraft.world.item.ItemStack.a(ItemStack.java:487)
[05:48:17] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:514)
[05:48:17] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2004)
[05:48:17] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28)
[05:48:17] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:8)
[05:48:17] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[05:48:17] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[05:48:17] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[05:48:17] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[05:48:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1426)
[05:48:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[05:48:17] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[05:48:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1403)
[05:48:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1396)
[05:48:17] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[05:48:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1374)
[05:48:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1256)
[05:48:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320)
[05:48:17] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[05:48:17] [Server thread/ERROR]: ATTENTION! There was an error adding the effect from the Electric Eel fish.
[05:48:17] [Server thread/ERROR]: ATTENTION! Check your config files and ensure spelling of the effect name is correct.
[05:48:17] [Server thread/ERROR]: ATTENTION! If the problem persists, ask for help on the support discord server.
```

Should be HARM?

**Comment by Oheers** [comment]
Cheers, I've set it to health: -1, harm was apparently killing players which was a bit extreme.
