### ISSUE TITLE
server internal error when trying to end a competition that should've ended.

### ISSUE THREAD

**Issue by TheLawOfNewt** [Oheers/EvenMoreFish#138]
18.06 23:14:06 [Server] ERROR null
18.06 23:14:06 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'emf' in plugin EvenMoreFish v1.5.0.52
18.06 23:14:06 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
18.06 23:14:06 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
18.06 23:14:06 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:900) ~[paper-1.19.jar:git-Paper-28]
18.06 23:14:06 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2376) ~[?:?]
18.06 23:14:06 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2147) ~[?:?]
18.06 23:14:06 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-28]
18.06 23:14:06 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
18.06 23:14:06 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
18.06 23:14:06 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-28]
18.06 23:14:06 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-28]
18.06 23:14:06 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
18.06 23:14:06 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-28]
18.06 23:14:06 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-28]
18.06 23:14:06 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
18.06 23:14:06 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-28]
18.06 23:14:06 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-28]
18.06 23:14:06 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-28]
18.06 23:14:06 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
18.06 23:14:06 [Server] INFO Caused by: java.lang.NoClassDefFoundError: me/clip/placeholderapi/PlaceholderAPI
18.06 23:14:06 [Server] INFO at com.oheers.fish.competition.reward.Reward.run(Reward.java:70) ~[even-more-fish-1.5.0.52.jar:?]
18.06 23:14:06 [Server] INFO at com.oheers.fish.competition.Competition.handleRewards(Competition.java:604) ~[even-more-fish-1.5.0.52.jar:?]
18.06 23:14:06 [Server] INFO at com.oheers.fish.competition.Competition.end(Competition.java:103) ~[even-more-fish-1.5.0.52.jar:?]
18.06 23:14:06 [Server] INFO at com.oheers.fish.Controls.competitionControl(CommandCentre.java:550) ~[even-more-fish-1.5.0.52.jar:?]
18.06 23:14:06 [Server] INFO at com.oheers.fish.Controls.adminControl(CommandCentre.java:271) ~[even-more-fish-1.5.0.52.jar:?]
18.06 23:14:06 [Server] INFO at com.oheers.fish.CommandCentre.control(CommandCentre.java:119) ~[even-more-fish-1.5.0.52.jar:?]
18.06 23:14:06 [Server] INFO at com.oheers.fish.CommandCentre.onCommand(CommandCentre.java:47) ~[even-more-fish-1.5.0.52.jar:?]
18.06 23:14:06 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
18.06 23:14:06 [Server] INFO ... 17 more
18.06 23:14:06 [Server] INFO Caused by: java.lang.ClassNotFoundException: me.clip.placeholderapi.PlaceholderAPI
18.06 23:14:06 [Server] INFO at com.oheers.fish.competition.reward.Reward.run(Reward.java:70) ~[even-more-fish-1.5.0.52.jar:?]
18.06 23:14:06 [Server] INFO at com.oheers.fish.competition.Competition.handleRewards(Competition.java:604) ~[even-more-fish-1.5.0.52.jar:?]
18.06 23:14:06 [Server] INFO at com.oheers.fish.competition.Competition.end(Competition.java:103) ~[even-more-fish-1.5.0.52.jar:?]
18.06 23:14:06 [Server] INFO at com.oheers.fish.Controls.competitionControl(CommandCentre.java:550) ~[even-more-fish-1.5.0.52.jar:?]
18.06 23:14:06 [Server] INFO at com.oheers.fish.Controls.adminControl(CommandCentre.java:271) ~[even-more-fish-1.5.0.52.jar:?]
18.06 23:14:06 [Server] INFO at com.oheers.fish.CommandCentre.control(CommandCentre.java:119) ~[even-more-fish-1.5.0.52.jar:?]
18.06 23:14:06 [Server] INFO at com.oheers.fish.CommandCentre.onCommand(CommandCentre.java:47) ~[even-more-fish-1.5.0.52.jar:?]
18.06 23:14:06 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]

**Comment by TheLawOfNewt** [comment]
it was fixed by installing PlaceHolderAPI.
