### ISSUE TITLE
MySQL is not using config username for database v3

### ISSUE THREAD

**Issue by mibby** [Oheers/EvenMoreFish#143]
EMF dev 57
https://ci.codemc.io/view/All/job/Oheers/job/EvenMoreFish/57/

Config
```
mysql:
  # Set to false if you're using a standard SQLITE .db file
  use-mysql: true
  # The address of the database (the port 3306 is automatically added in by default, if different: specify with address:port)
  address: localhost
  # The name of the database to store fish data in
  database: 'fish'
  # Login information
  username: 'fish'
  password: '--censored--'
```

Log
```
[00:14:07] [Server thread/ERROR]: [EvenMoreFish] Failed to create new tables or check for present tables.
[00:14:07] [Server thread/WARN]: java.sql.SQLException: Access denied for user 'mc4'@'localhost' (using password: NO)
[00:14:07] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[00:14:07] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[00:14:07] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
[00:14:07] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
[00:14:07] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
[00:14:07] [Server thread/WARN]: 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[00:14:07] [Server thread/WARN]: 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
[00:14:07] [Server thread/WARN]: 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:253)
[00:14:07] [Server thread/WARN]: 	at even-more-fish-1.5.0.56.jar//com.oheers.fish.database.DatabaseV3.getConnection(DatabaseV3.java:50)
[00:14:07] [Server thread/WARN]: 	at even-more-fish-1.5.0.56.jar//com.oheers.fish.database.DatabaseV3.createTables(DatabaseV3.java:103)
[00:14:07] [Server thread/WARN]: 	at even-more-fish-1.5.0.56.jar//com.oheers.fish.database.DatabaseV3.<init>(DatabaseV3.java:812)
[00:14:07] [Server thread/WARN]: 	at even-more-fish-1.5.0.56.jar//com.oheers.fish.EvenMoreFish.onEnable(EvenMoreFish.java:177)
[00:14:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[00:14:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[00:14:07] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536)
[00:14:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:600)
[00:14:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:514)
[00:14:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[00:14:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424)
[00:14:07] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:342)
[00:14:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1137)
[00:14:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307)
[00:14:07] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[00:14:07] [Server thread/INFO]: EvenMoreFish by Oheers : Enabled
```

'mc4' is the multicraft server instance created for linux user directory. There is no 'mc4' user in the MySQL.

**Comment by Oheers** [comment]
I'll have a look at this now. Cheers for reporting 👍

**Comment by Oheers** [comment]
Sure thing, I'm going to close this issue with a new commit and will add the ability to disable verbose output in the next commit.
