### ISSUE TITLE
NullPointerException: Cannot invoke "com.oheers.fish.database.UserReport.getFirstFish()" because "report" is null

### ISSUE THREAD

**Issue by mibby** [Oheers/EvenMoreFish#146]
EMF dev 58
https://ci.codemc.io/view/All/job/Oheers/job/EvenMoreFish/58/

Occurred when someone disconnected.

```
[00:51:09] [Server thread/INFO]: player lost connection: Disconnected
[00:51:09] [Craft Scheduler Thread - 121 - EvenMoreFish/WARN]: [EvenMoreFish] Plugin EvenMoreFish v1.5.0.57 generated an exception while executing task 39491
java.lang.NullPointerException: Cannot invoke "com.oheers.fish.database.UserReport.getFirstFish()" because "report" is null
	at com.oheers.fish.database.DatabaseV3.writeUserReport(DatabaseV3.java:569) ~[even-more-fish-1.5.0.57.jar:?]
	at com.oheers.fish.competition.JoinChecker$2.run(JoinChecker.java:111) ~[even-more-fish-1.5.0.57.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.jar:git-Purpur-1685]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.jar:git-Purpur-1685]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by CloudeLecaw** [comment]
I agree ingot this one too when Testing the build 59.

**Comment by CloudeLecaw** [comment]
jep dont forget to update to 1.6 :D
