### ISSUE TITLE
Fishing contest never ending

### ISSUE THREAD

**Issue by smuddgge** [Oheers/EvenMoreFish#162]
<img width="179" alt="Screenshot 2022-10-15 at 05 07 55" src="https://user-images.githubusercontent.com/68658429/195968044-24910e80-3699-4a51-be24-9eac8ccc1da3.png">

The fishing gets to -60 then loops back to 0 and starts again. You can fish while this is happening.

After trying to end a never-ending contest this error appears

```log
[03:51:16] [Server thread/INFO]: Smudyy issued server command: /emf admin competition end

...

[03:51:16 ERROR]: [EvenMoreFish] Could not increment competitions won for c824cc25-d891-45f9-92f7-5c4c4b776c37
[03:51:16 ERROR]: [EvenMoreFish] User: e4aa98b8-29c7-43cf-a071-e37958853ff5
[03:51:16 ERROR]: [EvenMoreFish] User: 7b9eee8b-7217-4e5f-bc44-fc1c543ce13a

...

null
org.bukkit.command.CommandException: Unhandled exception executing command 'emf' in plugin EvenMoreFish v1.6.3.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:962) ~[purpur-1.19.2.jar:git-Purpur-1814]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.2.jar:git-Purpur-1814]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2386) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2340) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1814]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1814]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1814]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1814]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1814]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1814]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1814]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1814]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.oheers.fish.database.UserReport.incrementCompetitionsJoined(int)" because the return value of "java.util.Map.get(Object)" is null
        at com.oheers.fish.competition.Competition.lambda$handleRewards$1(Competition.java:710) ~[even-more-fish-1.6.3.4.jar:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at com.oheers.fish.competition.Competition.handleRewards(Competition.java:710) ~[even-more-fish-1.6.3.4.jar:?]
        at com.oheers.fish.competition.Competition.end(Competition.java:111) ~[even-more-fish-1.6.3.4.jar:?]
        at com.oheers.fish.Controls.competitionControl(CommandCentre.java:632) ~[even-more-fish-1.6.3.4.jar:?]
        at com.oheers.fish.Controls.adminControl(CommandCentre.java:309) ~[even-more-fish-1.6.3.4.jar:?]
        at com.oheers.fish.CommandCentre.control(CommandCentre.java:174) ~[even-more-fish-1.6.3.4.jar:?]
        at com.oheers.fish.CommandCentre.onCommand(CommandCentre.java:89) ~[even-more-fish-1.6.3.4.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more
```

A few things have happened while the never-ending contest happened
```log
[03:32:47] [Craft Scheduler Thread - 4232 - EvenMoreFish/INFO]: [EvenMoreFish] _StxrryNxghts_ has joined for the first time, creating new data handle for them.
[03:32:47] [Craft Scheduler Thread - 4232 - EvenMoreFish/INFO]: [EvenMoreFish] User report for (b0d47337-45f1-4c98-914e-00228349f69f) does not exist in the database.
[03:32:47] [Craft Scheduler Thread - 4232 - EvenMoreFish/INFO]: [EvenMoreFish] Written empty user report for (b0d47337-45f1-4c98-914e-00228349f69f) to the database.
[03:32:47] [Craft Scheduler Thread - 4232 - EvenMoreFish/INFO]: [EvenMoreFish] Read user report for (b0d47337-45f1-4c98-914e-00228349f69f) from the database.
```

**Comment by exzolink** [comment]
@Oheers 
https://github.com/Oheers/EvenMoreFish/blob/master/src/main/java/com/oheers/fish/competition/Competition.java#L161
Change to <= 0

**Comment by Oheers** [comment]
Many thanks for that, what a simple fix x)
