### ISSUE TITLE
NullPointerException & SQLNonTransientConnectionException

### ISSUE THREAD

**Issue by mibby** [Oheers/EvenMoreFish#170]
EvenMoreFish dev 143
https://ci.codemc.io/view/All/job/Oheers/job/EvenMoreFish/143/

Two errors I noticed immediately after my server restarted and someone connected.
```
[11:01:50] [Craft Scheduler Thread - 30 - EvenMoreFish/WARN]: [EvenMoreFish] Plugin EvenMoreFish v1.6.5.7 generated an exception while executing task 7982
java.lang.NullPointerException: Cannot invoke "com.mysql.cj.protocol.ColumnDefinition.findColumn(String, boolean, int)" because "this.columnDefinition" is null
	at com.mysql.cj.jdbc.result.ResultSetImpl.findColumn(ResultSetImpl.java:581) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:851) ~[mysql-connector-java-8.0.29.jar:8.0.29]
	at com.oheers.fish.database.DatabaseV3.readUserReport(DatabaseV3.java:700) ~[even-more-fish-1.6.5.7.jar:?]
	at com.oheers.fish.competition.JoinChecker$1.run(JoinChecker.java:57) ~[even-more-fish-1.6.5.7.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

```
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/ERROR]: [EvenMoreFish] Failed to check database existence of user 4aa3f740-6a54-4e75-be90-85105fafb39e
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1647)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1563)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at even-more-fish-1.6.5.7.jar//com.oheers.fish.database.DatabaseV3.hasUser(DatabaseV3.java:502)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at even-more-fish-1.6.5.7.jar//com.oheers.fish.database.DatabaseV3.hasUser(DatabaseV3.java:490)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at even-more-fish-1.6.5.7.jar//com.oheers.fish.competition.JoinChecker$1.run(JoinChecker.java:43)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:761)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:568)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1578)
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/WARN]: 	... 10 more
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/ERROR]: [EvenMoreFish] Could not fetch user reports for: 4aa3f740-6a54-4e75-be90-85105fafb39e
[11:02:57] [Craft Scheduler Thread - 14 - EvenMoreFish/ERROR]: [EvenMoreFish] Null value when fetching data for user (xEllie),
UserReport: true,
FishReports: false
```

**Comment by Oheers** [comment]
Agh that's awkward, am I right in thinking you're running a MySQL database?

**Comment by Oheers** [comment]
Ah right, well I'm probably temporarily removing database support after Christmas so I can focus on other things, it's just taking too much time trying to fix the problems with it and getting nowhere.

**Comment by sarhatabaot** [comment]
Is this issue still occurring?

**Comment by sarhatabaot** [comment]
> Unfortunately this still happens, yes.

Can you try using https://github.com/Lapzupi/EvenMoreFish/releases/tag/database-issue-1 and lmk if the issue persists?
