### ISSUE TITLE
CommandException: Unhandled exception executing command 'emf' in plugin EvenMoreFish

### ISSUE THREAD

**Issue by mibby** [Oheers/EvenMoreFish#171]
EMF dev 148
https://ci.codemc.io/view/All/job/Oheers/job/EvenMoreFish/

Error occurs I assume because if the database is disabled in the config, it can't display the GUI. So should not display GUI by default when the command is ran if database is off?

```
[02:44:51] [Server thread/INFO]: player issued server command: /emf
[02:44:51] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'emf' in plugin EvenMoreFish v1.6.6.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:975) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.3.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:321) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:305) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2377) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2339) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.oheers.fish.database.DataManager.getFishReportsIfExists(java.util.UUID)" because the return value of "com.oheers.fish.database.DataManager.getInstance()" is null
	at com.oheers.fish.xmas2022.XmasGUI.setFish(XmasGUI.java:80) ~[even-more-fish-1.6.6.2.jar:?]
	at com.oheers.fish.xmas2022.XmasGUI.<init>(XmasGUI.java:44) ~[even-more-fish-1.6.6.2.jar:?]
	at com.oheers.fish.CommandCentre.onCommand(CommandCentre.java:84) ~[even-more-fish-1.6.6.2.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	... 23 more
```

**Comment by smuddgge** [comment]
This error is normally because the plugin is disabled, there should be a error before it that is different :3

**Comment by Oheers** [comment]
Apologies for the lack of response, I just missed the issues on github completely. I've since pushed out a new version to Spigot that puts the advent calendar behind an /emf xmas command instead. Very sorry about the awkwardness of the update, and thanks for your patience :)

**Comment by Oheers** [comment]
Yeah definitely 👍
