### ISSUE TITLE
Unable to break fish player head placed.

### ISSUE THREAD

**Issue by mibby** [Oheers/EvenMoreFish#173]
EMF dev 148
https://ci.codemc.io/view/All/job/Oheers/job/EvenMoreFish/

Report from a player that they are unable to break a fish head placed, which might be from a Jellyfish (months old)? They claim other heads are fine, just this one has problems. Removing Jellyfish from the fish config doesn't fix the problem of being unable to break. The rarity config "Rare" does exist in rarities.yml.

Specifically the head that looks like this, you are unable to break it in survival to pick it back up or just break it entirely.
![link](https://i.imgur.com/yqkys6n.png)

EMF outputs this error and prevents the breaking.

```
[06:17:40] [Server thread/ERROR]: Could not pass event BlockBreakEvent to EvenMoreFish v1.6.6.2
java.lang.NullPointerException: Cannot invoke "com.oheers.fish.fishing.items.Rarity.getValue()" because "this.rarity" is null
	at com.oheers.fish.fishing.items.Fish.<init>(Fish.java:73) ~[even-more-fish-1.6.6.2.jar:?]
	at com.oheers.fish.FishUtils.getFish(FishUtils.java:134) ~[even-more-fish-1.6.6.2.jar:?]
	at com.oheers.fish.SkullSaver.onBreak(SkullSaver.java:41) ~[even-more-fish-1.6.6.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1181.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1876]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:369) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:328) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:292) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1952) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Oheers** [comment]
Thanks for your patience in the delayed response, does the Jellyfish's rarity exist in your rarities.yml file?

**Comment by Oheers** [comment]
Ahh I see, so the Jellyfish was an Uncommon rarity, which was stored in the placed head. Now the plugin's looking for the rarity in the rarities.yml file but can't find it. The best way around this would be to add the Uncommon rarity back to the rarities.yml file with a weight of **0**. I've attached how it looked below.

```yaml
Uncommon:
    weight: 0
    colour: '&b'
    worth-multiplier: 0.2
    broadcast: false
    use-this-casing: false
    size:
      minSize: 20
      maxSize: 150
```

**Comment by madebygood** [comment]
I'm running into these bugs all over my head.

I think the ability to prevent break is unnecessary.

**Comment by sarhatabaot** [comment]
I'm guessing this is caused due to improper nbt. 
When a "head" fish is placed the block placed does not have fish nbt. I'll write something to fix this.

**Comment by sarhatabaot** [comment]
> @sarhatabaot @Oheers This is still occurring as of EMF dev 166.
> 
> ```
> [10:09:31] [Server thread/ERROR]: Could not pass event BlockBreakEvent to EvenMoreFish v1.6.10.2
> java.lang.NullPointerException: Cannot invoke "com.oheers.fish.fishing.items.Rarity.getValue()" because "this.rarity" is null
> 	at com.oheers.fish.fishing.items.Fish.<init>(Fish.java:68) ~[even-more-fish-1.6.10.2.jar:?]
> 	at com.oheers.fish.FishUtils.getFish(FishUtils.java:130) ~[even-more-fish-1.6.10.2.jar:?]
> 	at com.oheers.fish.SkullSaver.onBreak(SkullSaver.java:44) ~[even-more-fish-1.6.10.2.jar:?]
> 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor711.execute(Unknown Source) ~[?:?]
> 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
> 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1919]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
> 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.3.jar:git-Purpur-1919]
> 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.3.jar:git-Purpur-1919]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
> 	at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:369) ~[?:?]
> 	at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:328) ~[?:?]
> 	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:292) ~[?:?]
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1952) ~[?:?]
> 	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
> 	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
> 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
> 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1919]
> 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
> 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1919]
> 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1919]
> 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1919]
> 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1919]
> 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.3.jar:git-Purpur-1919]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.3.jar:git-Purpur-1919]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1919]
> 	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
> ```

Does this happen with old placed fish? Or new ones as well?

**Comment by sarhatabaot** [comment]
That must be it then. I tried to account for old placed items as well, but their nbt data is broken.

We could add a solution where we try and match the display name to the id of the fish. 

But that would add unnecessary complexity, and may not even work in some cases. 

It may be more appropriate to have the fix for this be in a separate branch not merged back to main.
