### ISSUE TITLE
Players occasionally get normal fish in a fishing competition

### ISSUE THREAD

**Issue by smuddgge** [Oheers/EvenMoreFish#175]
# Version
```
EvenMoreFish by Oheers 1.6.6.2
MCV: git-Purpur-1845 (MC: 1.19.2)
SSV: 1.19.2-R0.1-SNAPSHOT
Online: false
Loaded: Rarities(6) Fish(80) Baits(5) Competitions(168)
Database Engine: V3
```

# Important Configuration
`competitions.yml`
```yaml
allowed-rarities:
    - "Epic"
    - "Legendary"
    - "Ancient"
```
As seen, Christmas fish are not in competition.

# How to recreate

Since Christmas was over when you fish in a competition: 
on average you will catch 2 regular fish that are not from the plugin!

# Expected

All the fish caught should be from the plugin.

**Comment by smuddgge** [comment]
Not sure if this is the error, but just got this error!
```
[20:01:17 ERROR]: Could not pass event PlayerFishEvent to EvenMoreFish v1.6.6.2-DEV
java.lang.NullPointerException: Cannot invoke "com.oheers.fish.fishing.items.Fish.getName()" because the return value of "java.util.Map.get(Object)" is null
        at com.oheers.fish.fishing.FishingProcessor.hasCaughtTodaysXmas(FishingProcessor.java:383) ~[even-more-fish-1.6.6.2-DEV.jar:?]
        at com.oheers.fish.fishing.FishingProcessor.randomWeightedRarity(FishingProcessor.java:348) ~[even-more-fish-1.6.6.2-DEV.jar:?]
        at com.oheers.fish.fishing.FishingProcessor.chooseNonBaitFish(FishingProcessor.java:129) ~[even-more-fish-1.6.6.2-DEV.jar:?]
        at com.oheers.fish.fishing.FishingProcessor.getFish(FishingProcessor.java:198) ~[even-more-fish-1.6.6.2-DEV.jar:?]
        at com.oheers.fish.fishing.FishingProcessor.process(FishingProcessor.java:73) ~[even-more-fish-1.6.6.2-DEV.jar:?]
        at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1845]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.projectile.FishingHook.retrieve(FishingHook.java:507) ~[?:?]
        at net.minecraft.world.item.FishingRodItem.use(FishingRodItem.java:32) ~[?:?]
        at net.minecraft.world.item.ItemStack.use(ItemStack.java:500) ~[purpur-1.19.2.jar:git-Purpur-1845]
        at net.minecraft.server.level.ServerPlayerGameMode.useItem(ServerPlayerGameMode.java:473) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2131) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:32) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1845]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1845]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1845]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1845]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1845]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1845]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1845]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1845]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
        ```

**Comment by Oheers** [comment]
Oops, I forgot about the fish-catching part of the update. I'll push a second one out to Spigot tomorrow when I get a chance.

**Comment by sarhatabaot** [comment]
Fixed but issue never closed.
