### ISSUE TITLE
Error reporting at the end of fishing competition

### ISSUE THREAD

**Issue by KioProject123** [Oheers/EvenMoreFish#179]
Database not used.
```
java.lang.NullPointerException: Cannot invoke "com.oheers.fish.database.DataManager.getUserReportIfExists(java.util.UUID)" because the return value of "com.oheers.fish.database.DataManager.getInstance()" is null
	at com.oheers.fish.competition.Competition.handleRewards(Competition.java:662) ~[[KioCG]even-more-fish-1.6.8.jar:?]
	at com.oheers.fish.competition.Competition.end(Competition.java:112) ~[[KioCG]even-more-fish-1.6.8.jar:?]
	at com.oheers.fish.competition.Competition.processCompetitionSecond(Competition.java:162) ~[[KioCG]even-more-fish-1.6.8.jar:?]
	at com.oheers.fish.competition.Competition.decreaseTime(Competition.java:216) ~[[KioCG]even-more-fish-1.6.8.jar:?]
	at com.oheers.fish.competition.Competition.access$000(Competition.java:29) ~[[KioCG]even-more-fish-1.6.8.jar:?]
	at com.oheers.fish.competition.Competition$2.run(Competition.java:143) ~[[KioCG]even-more-fish-1.6.8.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[petal-1.19.3.jar:git-petal-"38af9cf"]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[petal-1.19.3.jar:git-petal-"38af9cf"]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1501) ~[petal-1.19.3.jar:git-petal-"38af9cf"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[petal-1.19.3.jar:git-petal-"38af9cf"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1425) ~[petal-1.19.3.jar:git-petal-"38af9cf"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[petal-1.19.3.jar:git-petal-"38af9cf"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[petal-1.19.3.jar:git-petal-"38af9cf"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Oheers** [comment]
Apologies for missing this, this should have been fixed in the latest version.
