### ISSUE TITLE
Error while plugin gets disabled

### ISSUE THREAD

**Issue by DEADLYDEVIL-IR** [Oheers/EvenMoreFish#183]
`[09:04:08] [Server thread/ERROR]: Error occurred while disabling EvenMoreFish v1.6.9.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.oheers.fish.database.DataManager.uncacheAll()" because the return value of "com.oheers.fish.database.DataManager.getInstance()" is null
	at com.oheers.fish.EvenMoreFish.saveUserData(EvenMoreFish.java:352) ~[even-more-fish-1.6.9.1.jar:?]
	at com.oheers.fish.EvenMoreFish.onDisable(EvenMoreFish.java:219) ~[even-more-fish-1.6.9.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:400) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:581) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:558) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.disablePlugins(CraftServer.java:512) ~[paper-1.19.3.jar:git-Paper-378]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:944) ~[paper-1.19.3.jar:git-Paper-378]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:797) ~[paper-1.19.3.jar:git-Paper-378]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[paper-1.19.3.jar:git-Paper-378]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-378]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

Hello, whenever I try to stop my server I get this error.

I don't really know will it even do anything to the datas or not but it's better to not see any errors in the server.

**Comment by Oheers** [comment]
Hi there, this is fixed in the latest dev build, available on the [jenkins build server](https://ci.codemc.io/job/Oheers/job/EvenMoreFish/).
