### ISSUE TITLE
Error on mohist 1.16.5

### ISSUE THREAD

**Issue by Eug3nK** [Oheers/EvenMoreFish#184]
Could not pass event PlayerFishEvent to EvenMoreFish v1.6.10
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303) ~[forge:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[forge:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:593) ~[forge:?]
        at net.minecraft.entity.projectile.FishingBobberEntity.func_146034_e(FishingBobberEntity.java:463) ~[?:?]
        at net.minecraft.item.FishingRodItem.func_77659_a(FishingRodItem.java:25) ~[?:?]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:243) ~[?:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:353) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147346_a(ServerPlayNetHandler.java:1482) ~[?:?]
        at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(CPlayerTryUseItemPacket.java:30) ~[?:?]
        at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(CPlayerTryUseItemPacket.java:9) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:939) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:176) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:922) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:916) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:902) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:822) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.block.Biome.MINECRAFT_PLAINS
        at java.lang.Enum.valueOf(Enum.java:240) ~[?:?]
        at org.bukkit.block.Biome.valueOf(Biome.java:11) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlock.biomeBaseToBiome(CraftBlock.java:522) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.getBiome(CraftWorld.java:935) ~[forge:7e29f765-296df566-9fb885e8]
        at com.oheers.fish.requirements.Biome.requirementMet(Biome.java:36) ~[?:?]
        at com.oheers.fish.fishing.FishingProcessor.getFish(FishingProcessor.java:425) ~[?:?]
        at com.oheers.fish.fishing.FishingProcessor.chooseNonBaitFish(FishingProcessor.java:132) ~[?:?]
        at com.oheers.fish.fishing.FishingProcessor.getFish(FishingProcessor.java:191) ~[?:?]
        at com.oheers.fish.fishing.FishingProcessor.process(FishingProcessor.java:70) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor207.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[forge:?]
        ... 24 more

**Comment by sarhatabaot** [comment]
Please try using the latest version and let us know if the issue persists.

**Comment by sarhatabaot** [comment]
Closed for inactivity.
