### ISSUE TITLE
Error since newest Paper Builds

### ISSUE THREAD

**Issue by PanetiX** [Oheers/EvenMoreFish#229]
I get this error since update Paper to latest version:

[22:20:07] [Server thread/WARN]: [EvenMoreFish] Task #10838013 for EvenMoreFish v1.6.11.14 generated an exception
java.lang.NullPointerException: Cannot invoke "com.oheers.fish.config.messages.Message.broadcast(org.bukkit.entity.Player, boolean, boolean)" because the return value of "com.oheers.fish.competition.Competition.getStartMessage()" is null
    at com.oheers.fish.competition.JoinChecker.lambda$onJoin$0(JoinChecker.java:83) ~[even-more-fish-1.6.11.14.jar:?]
    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-158]
    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-158]
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-158]
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-158]
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-158]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-158]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-158]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by sarhatabaot** [comment]
Can you re-name your messages.yml to message.yml.old and allow the default file to re-generate?

**Comment by sarhatabaot** [comment]
Closed for inactivity.
