### ISSUE TITLE
An Error help.

### ISSUE THREAD

**Issue by shamgamer** [Oheers/EvenMoreFish#236]
Runnig Paper 1.20.2.

[16:47:48 INFO]: [EvenMoreFish] Enabling EvenMoreFish v1.6.11.3
[16:47:49 INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_20_R2! Trying to find NMS support
[16:47:49 WARN]: [NBTAPI] [NBTAPI] This Server-Version(v1_20_R2) is not supported by this NBT-API Version(2.11.3) located in EvenMoreFish. The NBT-API will try to work as good as it can! Some functions may not work!
[16:47:49 INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[16:47:49 ERROR]: Error occurred while enabling EvenMoreFish v1.6.11.3 (Is it up to date?)
com.oheers.fish.utils.nbt.NbtApiException: [?]Error while calling the method 'getTagType(java.lang.String)', loaded: true, Enum: COMPOUND_GET_TYPE, Passed Class: class java.lang.Boolean
        at com.oheers.fish.utils.nbt.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:358) ~[even-more-fish-1.6.11.3.jar:?]
        at com.oheers.fish.utils.nbt.NBTReflectionUtil.getData(NBTReflectionUtil.java:635) ~[even-more-fish-1.6.11.3.jar:?]
        at com.oheers.fish.utils.nbt.NBTCompound.getType(NBTCompound.java:1016) ~[even-more-fish-1.6.11.3.jar:?]
        at com.oheers.fish.utils.nbt.NBTCompound.addCompound(NBTCompound.java:669) ~[even-more-fish-1.6.11.3.jar:?]
        at com.oheers.fish.FishUtils.get(FishUtils.java:229) ~[even-more-fish-1.6.11.3.jar:?]
        at com.oheers.fish.utils.ItemFactory.checkHead64(ItemFactory.java:162) ~[even-more-fish-1.6.11.3.jar:?]
        at com.oheers.fish.utils.ItemFactory.getType(ItemFactory.java:94) ~[even-more-fish-1.6.11.3.jar:?]
        at com.oheers.fish.utils.ItemFactory.<init>(ItemFactory.java:42) ~[even-more-fish-1.6.11.3.jar:?]
        at com.oheers.fish.fishing.items.Fish.<init>(Fish.java:75) ~[even-more-fish-1.6.11.3.jar:?]
        at com.oheers.fish.fishing.items.Names.loadRarities(Names.java:69) ~[even-more-fish-1.6.11.3.jar:?]
        at com.oheers.fish.EvenMoreFish.onEnable(EvenMoreFish.java:157) ~[even-more-fish-1.6.11.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-241]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-241]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-241]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-241]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.oheers.fish.utils.nbt.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:355) ~[even-more-fish-1.6.11.3.jar:?]
        ... 22 more
[16:47:49 INFO]: [EvenMoreFish] Disabling EvenMoreFish v1.6.11.3
[16:47:49 INFO]: [EvenMoreFish] EvenMoreFish by Oheers : Disabled

**Comment by FireML** [comment]
an update to fix this has been released on [spigot](https://www.spigotmc.org/resources/evenmorefish-%E2%96%AA-extensive-fishing-plugin-%E2%96%AA.91310/updates)

**Comment by sarhatabaot** [comment]
Fixed
