### ISSUE TITLE
1.20.2

### ISSUE THREAD

**Issue by HighPriestKing** [Oheers/EvenMoreFish#237]
[14:44:47 ERROR]: Error occurred while enabling EvenMoreFish v1.6.11.3 (Is it up to date?)
com.oheers.fish.utils.nbt.NbtApiException: [?]Error while calling the method 'getTagType(java.lang.String)', loaded: true, Enum: COMPOUND_GET_TYPE, Passed Class: class java.lang.Boolean
        at com.oheers.fish.utils.nbt.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:358) ~[even-more-fish-1.6.11.3.jar:?]
        at com.oheers.fish.utils.nbt.NBTReflectionUtil.getData(NBTReflectionUtil.java:635) ~[even-more-fish-1.6.11.3.jar:?]
        at com.oheers.fish.utils.nbt.NBTCompound.getType(NBTCompound.java:1016) ~[even-more-fish-1.6.11.3.jar:?]
        at com.oheers.fish.utils.nbt.NBTCompound.addCompound(NBTCompound.java:669) ~[even-more-fish-1.6.11.3.jar:?]
        at com.oheers.fish.utils.nbt.NBTCompound.getOrCreateCompound(NBTCompound.java:709) ~[even-more-fish-1.6.11.3.jar:?]
        at com.oheers.fish.EvenMoreFish.createCustomNBTRod(EvenMoreFish.java:367) ~[even-more-fish-1.6.11.3.jar:?]
        at com.oheers.fish.EvenMoreFish.onEnable(EvenMoreFish.java:132) ~[even-more-fish-1.6.11.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-241]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-241]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-241]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-241]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@4f123595
        at jdk.internal.reflect.GeneratedMethodAccessor67.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.oheers.fish.utils.nbt.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:355) ~[even-more-fish-1.6.11.3.jar:?]
        ... 18 more

**Comment by JeBobs** [comment]
I pushed a change to [my fork of the project that helps fix this](https://github.com/JeBobs/EvenMoreFish).
Not sure if the original authors want these changes since they know the code better than I do (and probably already have their own 1.20.2 changes in the works), but if you want to compile a build for the time being, first make sure both Adoptium JDK 8 and 17 are installed, clone the fork, then run:

> gradlew :even-more-fish-api:clean build
> gradlew build

Then once that's done you'll find the jar in even-more-fish-plugin\build\libs.

**Comment by sarhatabaot** [comment]
> I pushed a change to [my fork of the project that helps fix this](https://github.com/JeBobs/EvenMoreFish).
> Not sure if the original authors want these changes since they know the code better than I do (and probably already have their own 1.20.2 changes in the works), but if you want to compile a build for the time being, first make sure both Adoptium JDK 8 and 17 are installed, clone the fork, then run:
> 
> > gradlew :even-more-fish-api:clean build
> > gradlew build
> 
> Then once that's done you'll find the jar in even-more-fish-plugin\build\libs. 

There is no need for any additional changes since it already works on latest dev build.
The Jenkins page does not work atm therefore the latest dev build is on my branch temporarily.

**Comment by FireML** [comment]
an official update has been released on [spigot](https://www.spigotmc.org/resources/evenmorefish-%E2%96%AA-extensive-fishing-plugin-%E2%96%AA.91310/updates)
