### ISSUE TITLE
Random error while fishing in a competition

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [Oheers/EvenMoreFish#248]
No idea when exactly it happens, I just noticed it happening quite a few times through automated competitions.
`[19:01:39 ERROR]: Could not pass event PlayerFishEvent to EvenMoreFish v1.6.11.16
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at com.oheers.fish.baits.BaitNBTManager.randomBaitCatch(BaitNBTManager.java:262) ~[even-more-fish-1.6.11.16.jar:?]
        at com.oheers.fish.fishing.FishingProcessor.getFish(FishingProcessor.java:160) ~[even-more-fish-1.6.11.16.jar:?]
        at com.oheers.fish.fishing.FishingProcessor.process(FishingProcessor.java:69) ~[even-more-fish-1.6.11.16.jar:?]
        at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:40) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-193]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-193]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-193]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.projectile.FishingHook.retrieve(FishingHook.java:516) ~[?:?]
        at net.minecraft.world.item.FishingRodItem.use(FishingRodItem.java:32) ~[?:?]
        at net.minecraft.world.item.ItemStack.use(ItemStack.java:546) ~[paper-1.20.1.jar:git-Paper-193]
        at net.minecraft.server.level.ServerPlayerGameMode.useItem(ServerPlayerGameMode.java:481) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2096) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:32) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-193]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-193]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-193]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-193]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-193]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1286) ~[paper-1.20.1.jar:git-Paper-193]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.20.1.jar:git-Paper-193]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-193]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]`

I use paper 1.20.1#193 and the latest version of EMF, if any else files are required, please tell me so :).

**Comment by Oheers** [comment]
Hi there, incredibly sorry about the delay. Over the next two weeks when I'll have a bit of free time I'm going to try and collate togerther the biggest bugs with the plugin and get the plugin back into a working state. I've been very busy with studies and am aware EMF has been put onto the backburner massively which has been less than ideal for a lot of servers and many more players. I'm going to post a spigot update of where the current codebase of the plugin's at since there's been some work done by some really great contributors but hasn't been posted to the official spigot site yet - whichever bugs still exist on that version I'll try to tackle.

**Comment by sarhatabaot** [comment]
Closed in favor of #397
