### ISSUE TITLE
Plugin attempted to register task while disabled

### ISSUE THREAD

**Issue by duranaaron** [Oheers/EvenMoreFish#291]
When restarting the server an error appears.

**Error message:**
`[00:52:37 ERROR]: Error occurred while disabling EvenMoreFish v1.6.11.17
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.runDelayed(FoliaGlobalRegionScheduler.java:65) ~[pufferfish-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.run(FoliaGlobalRegionScheduler.java:53) ~[pufferfish-1.20.4.jar:?]
        at com.github.Anon8281.universalScheduler.foliaScheduler.FoliaScheduler.runTask(FoliaScheduler.java:49) ~[even-more-fish-1.6.11.17.jar:?]
        at com.oheers.fish.EvenMoreFish.saveUserData(EvenMoreFish.java:392) ~[even-more-fish-1.6.11.17.jar:?]
        at com.oheers.fish.EvenMoreFish.onDisable(EvenMoreFish.java:247) ~[even-more-fish-1.6.11.17.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:147) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.disablePlugins(CraftServer.java:570) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:975) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:825) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:930) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at org.spigotmc.WatchdogThread.run(WatchdogThread.java:231) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]`

**Comment by FireML** [comment]
This was fixed in #278. It'll be in the next release of the plugin 🙂

**Comment by sarhatabaot** [comment]
Fixed in #270
