### ISSUE TITLE
Winnings leaderboard not working when competition ends

### ISSUE THREAD

**Issue by CrispyDairy** [Oheers/EvenMoreFish#32]
A issue with the newest version of the plugin seems to have broken the leaderboard. When a competition ends, people get the rewards, but the leaderboard doesn't appear in chat. 

Error command in console:

[13:17:18 WARN]: [EvenMoreFish] Task #412289 for EvenMoreFish v1.2.0 generated an exception
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
        at com.oheers.fish.competition.reward.Reward.run(Reward.java:63) ~[?:?]
        at com.oheers.fish.competition.Competition.giveRewards(Competition.java:159) ~[?:?]
        at com.oheers.fish.competition.Competition.getLeaderboard(Competition.java:106) ~[?:?]
        at com.oheers.fish.competition.Competition.announceWinners(Competition.java:95) ~[?:?]
        at com.oheers.fish.competition.Competition.end(Competition.java:53) ~[?:?]
        at com.oheers.fish.competition.Ticker.run(Ticker.java:19) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-605]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-605]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1423) ~[patched_1.16.5.jar:git-Paper-605]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-605]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-605]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-605]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-605]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Oheers** [comment]
Could you provide the competition reward section of your config.yml please?

**Comment by CrispyDairy** [comment]
competitions:

  # When should competitions run?
  # It will use server's local timezone using a 24hour time format
  times:
    - "01:00" # midnight
    - "13:00" # midday

  # How long should the competition go on for? (In minutes)
  duration: 10

  # What colour should the bossbar cooldown be? (values can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/boss/BarColor.html)
  # Set the text and text colour above the bossbar in messages.yml
  bossbar-colour: GREEN

  winnings:
    1:
     # Commands are run by the console, it's advised to change these before releasing your server.
      - "COMMAND:eco give {player} 100"
      - "MESSAGE:&aCongratulations for coming 1st! &a$100 &ehas been added to your account."
      # Can't contain decimals.
      # formatted as "effect_name,amplifier,duration"
      - "EFFECT:SPEED,2,5"
      - "EFFECT:JUMP_BOOST,2,5"
    2:
      - "MESSAGE:&bCongratulations for coming 2nd! &a$50 &ehas been added to your account."
      - "COMMAND:eco give {player} 50"
      - "EFFECT:SPEED,2,5"
    3:
      - "EFFECT:SPEED,1,5"
      - "MESSAGE:&eCongratulations for coming 3rd! &a$25 &ehas been added to your account."
      - "COMMAND:eco give {player} 25"
  # Add as many more places as you need

  # This is the minimum needed amount of players for an automatic competition to start.
  minimum-players: 4

**Comment by Oheers** [comment]
Hello, somebody else was also having a similar problem and it was caused by there being a "6" left in messages.yml on line 35. Once that's removed: the leaderboard will be able to show.

**Comment by CrispyDairy** [comment]
Its not there for me, line 35 is empty

**Comment by CrispyDairy** [comment]
Alright, thank you :)

**Comment by Oheers** [comment]
Hey there, I've just looked at the problem and it's caused by an incorrect potion name being given: use "JUMP" rather than "JUMP_BOOST"

In future generated config.ymls I've set a reference to the javadocs pertaining to potion effects but for now, a full list can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
