### ISSUE TITLE
Error occurred (in the plugin loader) while disabling EvenMoreFish v1.6.11.17 (Is it up to date?)

### ISSUE THREAD

**Issue by DexterSK** [Oheers/EvenMoreFish#329]
[16:14:05 ERROR]: Error occurred (in the plugin loader) while disabling EvenMoreFish v1.6.11.17 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.runDelayed(FoliaGlobalRegionScheduler.java:65) ~[purpur-1.20.2.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.run(FoliaGlobalRegionScheduler.java:53) ~[purpur-1.20.2.jar:?]
        at com.github.Anon8281.universalScheduler.foliaScheduler.FoliaScheduler.runTask(FoliaScheduler.java:49) ~[even-more-fish-1.6.11.17.jar:?]
        at com.oheers.fish.EvenMoreFish.saveUserData(EvenMoreFish.java:392) ~[even-more-fish-1.6.11.17.jar:?]
        at com.oheers.fish.EvenMoreFish.onDisable(EvenMoreFish.java:247) ~[even-more-fish-1.6.11.17.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:148) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.disablePlugins(CraftServer.java:589) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:943) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:858) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by sarhatabaot** [comment]
Please try using latest dev build: https://ci.codemc.io/job/Oheers/job/EvenMoreFish/lastBuild/

**Comment by FireML** [comment]
Fixed in the latest Spigot release, 1.7.
