### ISSUE TITLE
 [EvenMoreFish] Global task for EvenMoreFish v1.7 generated an exception

### ISSUE THREAD

**Issue by legendofgow** [Oheers/EvenMoreFish#355]
Random error on start competition, break plugin and dont work after, need server restart

Purpur 1.20.4
Java: 21

`[18:11:27 WARN]: [EvenMoreFish] Global task for EvenMoreFish v1.7 generated an exception
java.lang.NullPointerException: Cannot invoke "com.oheers.fish.config.messages.Message.broadcast(org.bukkit.entity.Player, boolean)" because the return value of "com.oheers.fish.competition.Competition.getStartMessage()" is null
        at com.oheers.fish.competition.JoinChecker.lambda$onJoin$1(JoinChecker.java:73) ~[even-more-fish-1.7.jar:?]
        at com.oheers.fish.libs.universalScheduler.foliaScheduler.FoliaScheduler.lambda$runTaskLater$1(FoliaScheduler.java:58) ~[even-more-fish-1.7.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[purpur-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[purpur-1.20.4.jar:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1682) ~[purpur-1.20.4.jar:git-Purpur-2174]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2174]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2174]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2174]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2174]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by sarhatabaot** [comment]
Are you still having this issue? Can you try using the latest dev build?

**Comment by sarhatabaot** [comment]
Closed for inactivity.
