### ISSUE TITLE
/emf admin migrate throws an exception

### ISSUE THREAD

**Issue by TomLewis** [Oheers/EvenMoreFish#364]
Finally trying to migrate from even-more-fish-1.5.0.29 to even-more-fish-1.7 using `/emf admin migrate`

Ive tried using the old configs with the database enabled, and ive tried fresh configs setup the database and copied over the old /data folder to convert. I have 50k player data to convert.

But no matter what I do it throws this error.

On purpur 1.18.2

```
[21:56:41] [Craft Scheduler Thread - 15 - EvenMoreFish/WARN]: [EvenMoreFish] Plugin EvenMoreFish v1.7 generated an exception while executing task 238
java.lang.NullPointerException: Cannot invoke "com.oheers.fish.database.DatabaseV3.migrateLegacy(org.bukkit.command.CommandSender)" because the return value of "com.oheers.fish.EvenMoreFish.getDatabaseV3()" is null
	at com.oheers.fish.commands.AdminCommand.lambda$onMigrate$1(AdminCommand.java:346) ~[even-more-fish-1.7.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

```

**Comment by sarhatabaot** [comment]
Please contact me on discord so we can properly resolve this issue.
