### ISSUE TITLE
Shop sell bug

### ISSUE THREAD

**Issue by pittaa** [Oheers/EvenMoreFish#388]
### Contact Details

jakub.pittauer@gmail.com

### What happened?

When I try to sell fish that I gave myself with /emf admin fish, it show this error. Fish that was caught can normally be sold.

### Version

1.7 (latest)

### Server Version

git-Pufferfish-51 (MC: 1.20.4)

### Java Version

17

### Relevant log output

```shell
[01:31:03] [Server thread/ERROR]: [EvenMoreFish] Exception while trying to run action for click on DynamicGuiElement in slot 30 of §2§lRYBÍ TRŽNICE GUI!
java.lang.IllegalArgumentException: Invalid UUID string: 
	at java.util.UUID.fromString1(UUID.java:280) ~[?:?]
	at java.util.UUID.fromString(UUID.java:258) ~[?:?]
	at com.oheers.fish.FishUtils.getFish(FishUtils.java:98) ~[even-more-fish-1.7.2.jar:?]
	at com.oheers.fish.selling.SellGUI.sell(SellGUI.java:423) ~[even-more-fish-1.7.2.jar:?]
	at com.oheers.fish.selling.SellGUI.lambda$getSellItemFromState$8(SellGUI.java:252) ~[even-more-fish-1.7.2.jar:?]
	at com.oheers.fish.libs.inventorygui.InventoryGui.handleInteract(InventoryGui.java:1179) ~[even-more-fish-1.7.2.jar:?]
	at com.oheers.fish.libs.inventorygui.InventoryGui.access$500(InventoryGui.java:83) ~[even-more-fish-1.7.2.jar:?]
	at com.oheers.fish.libs.inventorygui.InventoryGui$GuiListener.onInventoryClick(InventoryGui.java:1282) ~[even-more-fish-1.7.2.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:git-Pufferfish-51]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3120) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:25) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1472) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1449) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1372) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1350) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1239) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by FireML** [comment]
This issue has been fixed in dev builds and will be in the next release of the plugin.

If you want to use the dev build, you can get it from here: https://ci.codemc.io/job/Oheers/job/EvenMoreFish/ :slightly_smiling_face:
