### ISSUE TITLE
[Bug]: bait cant put on fishing rod if it is enchanted

### ISSUE THREAD

**Issue by lackooka** [Oheers/EvenMoreFish#397]
### Contact Details

discord: dlacoo

### What happened?

I want to put a bait into my fishing rod and I cant do it because i get a console error. I can put this same bait into a normal (not enchanted) fishing rod. 

### Version

1.7 (latest)

### Server Version

Purpur 1.21-2258

### Java Version

21

### Relevant log output

```shell
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at even-more-fish-1.7.2.jar/com.oheers.fish.baits.BaitNBTManager.newApplyLore(BaitNBTManager.java:361) ~[even-more-fish-1.7.2.jar:?]
        at even-more-fish-1.7.2.jar/com.oheers.fish.baits.BaitNBTManager.applyBaitedRodNBT(BaitNBTManager.java:205) ~[even-more-fish-1.7.2.jar:?]
        at even-more-fish-1.7.2.jar/com.oheers.fish.baits.BaitListener.onClickEvent(BaitListener.java:65) ~[even-more-fish-1.7.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1468.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2258-ff19bcc]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3204) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1576) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1553) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1546) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1656) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1337) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Relevant screenshots

![image](https://github.com/user-attachments/assets/09df6164-dc4f-4139-84af-cb119e45adeb)
![image](https://github.com/user-attachments/assets/db5fc73b-9b3a-4c45-a278-649cfcabff6e)

**Comment by sarhatabaot** [comment]
Can you try using the latest dev build first?

**Comment by lackooka** [comment]
if I can download .jar file, yes

**Comment by lackooka** [comment]
I tried with 1.7.3, but it still have a problem:

[12:23:27 ERROR]: Could not pass event InventoryClickEvent to EvenMoreFish v1.7.3
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at even-more-fish-1.7.3-1722169370397.jar/com.oheers.fish.baits.BaitNBTManager.newApplyLore(BaitNBTManager.java:360) ~[even-more-fish-1.7.3-1722169370397.jar:?]
        at even-more-fish-1.7.3-1722169370397.jar/com.oheers.fish.baits.BaitNBTManager.applyBaitedRodNBT(BaitNBTManager.java:204) ~[even-more-fish-1.7.3-1722169370397.jar:?]
        at even-more-fish-1.7.3-1722169370397.jar/com.oheers.fish.baits.BaitListener.onClickEvent(BaitListener.java:64) ~[even-more-fish-1.7.3-1722169370397.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1774.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2258-ff19bcc]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3204) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1576) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1553) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1546) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1505) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1627) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1337) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by sarhatabaot** [comment]
Noticed this issue with a lot of other ones, so closing everything else and linking them here:
https://github.com/Oheers/EvenMoreFish/issues/248
https://github.com/Oheers/EvenMoreFish/issues/352

**Comment by lackooka** [comment]
is it fixed or not?

**Comment by sarhatabaot** [comment]
> is it fixed or not?

We are working on a fix. When it's fixed, I'll post here 😁

**Comment by DavidDoesCode** [comment]
I think this commit will fix this issue:
https://github.com/Oheers/EvenMoreFish/compare/master...DavidDoesCode:EvenMoreFish:FIX-nbt-conversion-with-existing-meta-data

It does not currently save lore AFTER the item.
Also I do not know what other potential issue I may have caused with this.

![image](https://github.com/user-attachments/assets/6edcbbde-e1c6-489d-9576-5afe0516fcda)

**Comment by sarhatabaot** [comment]
> @lackooka @sarhatabaot I think this commit will fix this issue: [master...DavidDoesCode:EvenMoreFish:FIX-nbt-conversion-with-existing-meta-data](https://github.com/Oheers/EvenMoreFish/compare/master...DavidDoesCode:EvenMoreFish:FIX-nbt-conversion-with-existing-meta-data)
> 
> It does not currently save lore AFTER the item. Also I do not know what other potential issue I may have caused with this.
> 
> ![image](https://private-user-images.githubusercontent.com/51980803/383366286-6edcbbde-e1c6-489d-9576-5afe0516fcda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NzQxODUsIm5iZiI6MTczMDg3Mzg4NSwicGF0aCI6Ii81MTk4MDgwMy8zODMzNjYyODYtNmVkY2JiZGUtZTFjNi00ODlkLTk1NzYtNWFmZTA1MTZmY2RhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA2MTgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MTMwNTk0ODA2M2MxODU3NmI2ZjRiZDgxY2I2NmUwYjcyNDdhMWM0MmYyZDk5MTFmNDJkOTc1ZDE2NTNkMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bWCvAVaYEjYnkNcEK4s7afDaHWb0NBjAInzXz6ALEbI)

Great! Can you submit a PR? I will merge it
Since it's just for legacy nbt, I doubt it will cause any compat issues, but we will see with time
