### ISSUE TITLE
Database errors

### ISSUE THREAD

**Issue by Oheers** [Oheers/EvenMoreFish#41]
`[08:37:02] [Thread-1337/WARN]: java.sql.SQLException: The prepared statement has been finalized
[08:37:02] [Thread-1337/WARN]: 	at org.sqlite.core.NativeDB.throwex(NativeDB.java:487)
[08:37:02] [Thread-1337/WARN]: 	at org.sqlite.core.NativeDB.column_count(Native Method)
[08:37:02] [Thread-1337/WARN]: 	at org.sqlite.core.DB.column_names(DB.java:731)
[08:37:02] [Thread-1337/WARN]: 	at org.sqlite.jdbc3.JDBC3Statement.getResultSet(JDBC3Statement.java:131)
[08:37:02] [Thread-1337/WARN]: 	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:82)
[08:37:02] [Thread-1337/WARN]: 	at com.oheers.fish.database.Database.hasFish(Database.java:76)
[08:37:02] [Thread-1337/WARN]: 	at com.oheers.fish.fishing.FishEvent.run(FishEvent.java:211)
[08:37:02] [Thread-1337/WARN]: 	at java.lang.Thread.run(Unknown Source)
 
[08:37:57] [Thread-1359/WARN]: java.sql.SQLException: The database has been closed
[08:37:57] [Thread-1359/WARN]: 	at org.sqlite.core.NativeDB.throwex(NativeDB.java:487)
[08:37:57] [Thread-1359/WARN]: 	at org.sqlite.core.NativeDB.column_text_utf8(Native Method)
[08:37:57] [Thread-1359/WARN]: 	at org.sqlite.core.NativeDB.column_text(NativeDB.java:249)
[08:37:57] [Thread-1359/WARN]: 	at org.sqlite.jdbc3.JDBC3ResultSet.getString(JDBC3ResultSet.java:437)
[08:37:57] [Thread-1359/WARN]: 	at com.oheers.fish.database.Database.hasFish(Database.java:81)
[08:37:57] [Thread-1359/WARN]: 	at com.oheers.fish.fishing.FishEvent.run(FishEvent.java:211)
[08:37:57] [Thread-1359/WARN]: 	at java.lang.Thread.run(Unknown Source)`

**Comment by Oheers** [comment]
Fixed in a previous version
