### ISSUE TITLE
[Bug]: Could not pass event PlayerInteractEvent to EvenMoreFish v1.7.2

### ISSUE THREAD

**Issue by KoalaServers** [Oheers/EvenMoreFish#413]
### Contact Details

info@koalaservers.net

### What happened?

Error in console

### Version

1.7.2

### Server Version

1.21.1-15

### Java Version

1.8

### Relevant log output

```shell
[15:59:45] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EvenMoreFish v1.7.2
java.lang.NoClassDefFoundError: Could not initialize class com.oheers.fish.utils.nbtapi.NBTReflectionUtil
	at even-more-fish-1.7.2.jar/com.oheers.fish.utils.nbtapi.NBTCompound.hasTag(NBTCompound.java:720) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.utils.nbt.NbtVersion.lambda$getVersion$0(NbtVersion.java:34) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.utils.nbtapi.NBT.get(NBT.java:102) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.utils.nbt.NbtVersion.getVersion(NbtVersion.java:33) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.utils.nbt.NbtUtils.hasKey(NbtUtils.java:20) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.FishUtils.isFish(FishUtils.java:50) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.events.FishInteractEvent.interactEvent(FishInteractEvent.java:27) ~[even-more-fish-1.7.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1171.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-15-11b4ac7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:602) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:558) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:553) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:1933) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:47) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:10) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Server thread"]
	at java.base/java.util.ImmutableCollections$MapN.probe(ImmutableCollections.java:1328) ~[?:?]
	at java.base/java.util.ImmutableCollections$MapN.get(ImmutableCollections.java:1242) ~[?:?]
	at java.base/java.util.ImmutableCollections$AbstractImmutableMap.getOrDefault(ImmutableCollections.java:1097) ~[?:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflection.mapDeclaredFieldName(PaperReflection.java:79) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90) ~[reflection-rewriter-runtime-0.0.3.jar:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at even-more-fish-1.7.2.jar/com.oheers.fish.utils.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:59) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.utils.nbtapi.NBTCompound.hasTag(NBTCompound.java:720) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.utils.nbt.NbtVersion.lambda$getVersion$0(NbtVersion.java:34) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.utils.nbtapi.NBT.get(NBT.java:102) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.utils.nbt.NbtVersion.getVersion(NbtVersion.java:33) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.utils.nbt.NbtUtils.hasKey(NbtUtils.java:20) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.FishUtils.isFish(FishUtils.java:50) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.events.FishInteractEvent.interactEvent(FishInteractEvent.java:27) ~[even-more-fish-1.7.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1171.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-15-11b4ac7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:602) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:558) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:553) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:1933) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:47) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:10) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1629) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	... 2 more
[15:59:45] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EvenMoreFish v1.7.2
java.lang.NoClassDefFoundError: Could not initialize class com.oheers.fish.utils.nbtapi.NBTReflectionUtil
	at even-more-fish-1.7.2.jar/com.oheers.fish.utils.nbtapi.NBTCompound.hasTag(NBTCompound.java:720) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.utils.nbt.NbtVersion.lambda$getVersion$0(NbtVersion.java:34) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.utils.nbtapi.NBT.get(NBT.java:102) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.utils.nbt.NbtVersion.getVersion(NbtVersion.java:33) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.utils.nbt.NbtUtils.hasKey(NbtUtils.java:20) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.FishUtils.isFish(FishUtils.java:50) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.events.FishInteractEvent.interactEvent(FishInteractEvent.java:27) ~[even-more-fish-1.7.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1171.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-15-11b4ac7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:602) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:558) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:553) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleAnimate(ServerGamePacketListenerImpl.java:2508) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:34) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:16) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1588) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Server thread"]
	at java.base/java.util.ImmutableCollections$MapN.probe(ImmutableCollections.java:1328) ~[?:?]
	at java.base/java.util.ImmutableCollections$MapN.get(ImmutableCollections.java:1242) ~[?:?]
	at java.base/java.util.ImmutableCollections$AbstractImmutableMap.getOrDefault(ImmutableCollections.java:1097) ~[?:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflection.mapDeclaredFieldName(PaperReflection.java:79) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90) ~[reflection-rewriter-runtime-0.0.3.jar:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at even-more-fish-1.7.2.jar/com.oheers.fish.utils.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:59) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.utils.nbtapi.NBTCompound.hasTag(NBTCompound.java:720) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.utils.nbt.NbtVersion.lambda$getVersion$0(NbtVersion.java:34) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.utils.nbtapi.NBT.get(NBT.java:102) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.utils.nbt.NbtVersion.getVersion(NbtVersion.java:33) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.utils.nbt.NbtUtils.hasKey(NbtUtils.java:20) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.FishUtils.isFish(FishUtils.java:50) ~[even-more-fish-1.7.2.jar:?]
	at even-more-fish-1.7.2.jar/com.oheers.fish.events.FishInteractEvent.interactEvent(FishInteractEvent.java:27) ~[even-more-fish-1.7.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1171.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-15-11b4ac7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:602) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:558) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:553) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:1933) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:47) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:10) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1629) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
	... 3 more
```

**Comment by sarhatabaot** [comment]
Can you try using latest dev version?

**Comment by KoalaServers** [comment]
> Can you try using latest dev version?

Sure did you have a link for the dev builds?

**Comment by FireML** [comment]
> > Can you try using latest dev version?
> 
> Sure did you have a link for the dev builds?

https://ci.codemc.io/job/Oheers/job/EvenMoreFish/

**Comment by bertbaron** [comment]
I had similar stack traces in the log, and at least reloading the config did not work as a result of those. Just installed the latest dev build (1.7.3-106) and it looks good so far.

**Comment by sarhatabaot** [comment]
This issue seems to have been fixed in one of the dev versions. Closing for now.
