### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CinemaMC** [Oheers/EvenMoreFish#423]
### Contact Details

Discord: cinemamc

### What happened?

EMF is throwing some errors in my console. Plus, when I try to give myself bait using /emf admin bait Epic_Elixir 1 [player name], it also throws erors. I am also using the latest version of NBTAPI.

### Version

1.7.3

### Development Version

1.7.2

### Server Version

Paper version 1.21.1-40-master@2fdb2e9 (2024-08-21T01:35:33Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT) You are 17 version(s) behind Download the new version at: https://papermc.io/downloads/paper Previous version: git-Paper-22 (MC: 1.20.5)

### Java Version

1.8

### Relevant log output

```shell
[20:45:00 INFO]: CinemaMC issued server command: /emf admin bait Epic_Elixir 1
[20:45:00 ERROR]: [EvenMoreFish] [ACF] Exception in command: emf admin bait Epic_Elixir 1
[20:45:00 ERROR]: [EvenMoreFish] [ACF] java.lang.NoClassDefFoundError: Could not initialize class com.oheers.fish.utils.nbtapi.NBTReflectionUtil
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at even-more-fish-1.7.2.jar//com.oheers.fish.utils.nbtapi.NBTCompound.getType(NBTCompound.java:1348)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at even-more-fish-1.7.2.jar//com.oheers.fish.utils.nbtapi.NBTCompound.addCompound(NBTCompound.java:765)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at even-more-fish-1.7.2.jar//com.oheers.fish.utils.nbtapi.NBTCompound.getOrCreateCompound(NBTCompound.java:805)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at even-more-fish-1.7.2.jar//com.oheers.fish.utils.nbtapi.NBTCompound.getOrCreateCompound(NBTCompound.java:33)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at even-more-fish-1.7.2.jar//com.oheers.fish.baits.BaitNBTManager.lambda$applyBaitNBT$0(BaitNBTManager.java:73)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at even-more-fish-1.7.2.jar//com.oheers.fish.utils.nbtapi.NBT.modify(NBT.java:248)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at even-more-fish-1.7.2.jar//com.oheers.fish.baits.BaitNBTManager.applyBaitNBT(BaitNBTManager.java:72)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at even-more-fish-1.7.2.jar//com.oheers.fish.baits.Bait.create(Bait.java:83)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at even-more-fish-1.7.2.jar//com.oheers.fish.commands.AdminCommand.onBait(AdminCommand.java:210)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at even-more-fish-1.7.2.jar//com.oheers.fish.libs.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at even-more-fish-1.7.2.jar//com.oheers.fish.libs.acf.BaseCommand.executeCommand(BaseCommand.java:578)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at even-more-fish-1.7.2.jar//com.oheers.fish.libs.acf.BaseCommand.execute(BaseCommand.java:513)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at even-more-fish-1.7.2.jar//com.oheers.fish.libs.acf.RootCommand.execute(RootCommand.java:99)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at even-more-fish-1.7.2.jar//com.oheers.fish.libs.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.commands.Commands.performCommand(Commands.java:350)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.commands.Commands.performCommand(Commands.java:337)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.commands.Commands.performCommand(Commands.java:332)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2218)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2192)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1629)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at java.base/java.lang.Thread.run(Thread.java:1583)
[20:45:00 ERROR]: [EvenMoreFish] [ACF] Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Server thread"]
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at java.base/java.util.ImmutableCollections$MapN.probe(ImmutableCollections.java:1328)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at java.base/java.util.ImmutableCollections$MapN.get(ImmutableCollections.java:1242)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at java.base/java.util.ImmutableCollections$AbstractImmutableMap.getOrDefault(ImmutableCollections.java:1097)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at io.papermc.paper.pluginremap.reflect.PaperReflection.mapDeclaredFieldName(PaperReflection.java:79)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at even-more-fish-1.7.2.jar//com.oheers.fish.utils.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:59)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at even-more-fish-1.7.2.jar//com.oheers.fish.utils.nbtapi.NBTCompound.hasTag(NBTCompound.java:720)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at even-more-fish-1.7.2.jar//com.oheers.fish.utils.nbt.NbtVersion.lambda$getVersion$0(NbtVersion.java:34)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at even-more-fish-1.7.2.jar//com.oheers.fish.utils.nbtapi.NBT.get(NBT.java:102)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at even-more-fish-1.7.2.jar//com.oheers.fish.utils.nbt.NbtVersion.getVersion(NbtVersion.java:33)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at even-more-fish-1.7.2.jar//com.oheers.fish.utils.nbt.NbtUtils.hasKey(NbtUtils.java:20)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at even-more-fish-1.7.2.jar//com.oheers.fish.FishUtils.isFish(FishUtils.java:50)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at even-more-fish-1.7.2.jar//com.oheers.fish.events.FishInteractEvent.interactEvent(FishInteractEvent.java:27)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor736.execute(Unknown Source)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:604)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:560)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:555)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:204)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1856)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318)
[20:45:00 ERROR]: [EvenMoreFish] [ACF]  ... 2 more
```

**Comment by FireML** [comment]
1.21.1 is not officially supported yet, please use [dev builds](https://ci.codemc.io/job/Oheers/job/EvenMoreFish/) or wait for a 1.21.1 release :slightly_smiling_face:

**Comment by sarhatabaot** [comment]
Fixed in latest builds :)
