### ISSUE TITLE
exception when eating a fish with a potion effect as an eat-event

### ISSUE THREAD

**Issue by LeeSpork** [Oheers/EvenMoreFish#67]
Eating a fish with a potion effect as an eat-event doesn't work.

### My fish:
```
    Levi-Fish:
      item:
        material: TROPICAL_FISH
      biomes:
        - THE_END
        - END_BARRENS
        - END_HIGHLANDS
        - END_MIDLANDS
        - THE_VOID
      eat-event:
        - "EFFECT:LEVITATION,1,5"
```

### Console log:
```
[18:24:34 INFO]: <LeeSpork> Eating a levi-fish
[18:24:39 WARN]: [EvenMoreFish] Plugin EvenMoreFish v1.3.3 generated an exception while executing task 230
java.lang.IllegalStateException: Asynchronous effect add!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
	at net.minecraft.world.entity.EntityLiving.addEffect(EntityLiving.java:1084) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
	at net.minecraft.world.entity.EntityLiving.addEffect(EntityLiving.java:1076) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
	at org.bukkit.craftbukkit.v1_17_R1.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:363) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
	at org.bukkit.craftbukkit.v1_17_R1.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:358) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
	at com.oheers.fish.competition.reward.Reward.run(Reward.java:63) ~[?:?]
	at com.oheers.fish.events.FishEatEvent$1.run(FishEatEvent.java:36) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.17.1.jar:3219-Spigot-b166a49-8c6d60c]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[18:24:40 INFO]: <LeeSpork> nothing happened
```

**Comment by Oheers** [comment]
Thanks for reporting, this bug will be fixed in the next update or I can send you a snapshot on the support discord if you'd rather have the fix sooner rather than later.
