### ISSUE TITLE
Sometimes fish.give() returns air

### ISSUE THREAD

**Issue by exzolink** [Oheers/EvenMoreFish#85]
Hi!
Sometimes fish.give() returns air

[16:47:25 ERROR]: Could not pass event PlayerFishEvent to EvenMoreFish v1.4.0.22
java.lang.IllegalArgumentException: Cannot drop air
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.16.5.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.EntityItem.setItemStack(EntityItem.java:501) ~[patched_1.16.5.jar:git-Airplane-11]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftItem.setItemStack(CraftItem.java:37) ~[patched_1.16.5.jar:git-Airplane-11]
        at com.oheers.fish.fishing.FishingProcessor.process(FishingProcessor.java:119) ~[?:?]
        at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.16.5.jar:git-Airplane-11]

**Comment by Oheers** [comment]
It is indeed on the master branch.

**Comment by exzolink** [comment]
This did not happen before competition rewrite, i guess something wrong with rarity rolling

**Comment by exzolink** [comment]
I dont have fishes with air material

**Comment by Oheers** [comment]
Oh I see, could you first ensure that this issue doesn't occurr in the latest version, and if it does please send your fish.yml & rarities.yml (if you would rather not post it publically, feel free to open a ticket in #private-support on the discord)
