### ISSUE TITLE
Xmas particles error

### ISSUE THREAD

**Issue by exzolink** [Oheers/EvenMoreFish#97]
`
[03:20:23 ERROR]: Could not pass event PlayerFishEvent to EvenMoreFish v1.4.2.1
java.lang.NoClassDefFoundError: Could not initialize class com.oheers.fish.xmas2021.ParticleEngine
        at com.oheers.fish.fishing.FishingProcessor.process(FishingProcessor.java:191) ~[?:?]
        at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[server.jar:git-Airplane-11]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[server.jar:git-Airplane-11]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Airplane-11]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[server.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.ItemFishingRod.a(ItemFishingRod.java:44) ~[server.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.ItemStack.a(ItemStack.java:434) ~[server.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:482) ~[server.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1869) ~[?:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:32) ~[server.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:9) ~[server.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[server.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[server.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[server.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[server.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1325) ~[server.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1318) ~[server.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[server.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1294) ~[server.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1138) ~[server.jar:git-Airplane-11]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[server.jar:git-Airplane-11]
        at java.lang.Thread.run(Thread.java:831) [?:?]
`

**Comment by Oheers** [comment]
This particle feature no longer exists in the plugin, but has been noted for when it's re-added in the future.
